"""스캔 처리, 입출력, 화면 및 평가 도구가 공유하는 고정값입니다."""

SUPPORTED_IMAGE_SUFFIXES = ('.png', '.jpg', '.jpeg')
STAGE_IMAGE_SUFFIX = '.png'
MAX_PIXEL_VALUE = 255
GRAYSCALE_LEVELS = MAX_PIXEL_VALUE + 1
MIN_IMAGE_SIZE = 3
DOCUMENT_CORNER_COUNT = 4
MAX_BLUR_SIZE = 51

STAGE_ORIGINAL = '01_original'
STAGE_PREPROCESSED = '02_preprocessed'
STAGE_EDGES = '03_edges'
STAGE_CONTOURS = '04_contours'
STAGE_WARPED = '05_warped'
STAGE_RESULT = '06_result'
OUTPUT_STAGES = (STAGE_WARPED, STAGE_RESULT)
SCAN_STAGES = (
    STAGE_ORIGINAL,
    STAGE_PREPROCESSED,
    STAGE_EDGES,
    STAGE_CONTOURS,
    *OUTPUT_STAGES,
)
